name: Frontend CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Node version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Node version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # TODO: Replace with your actual deployment command, e.g.:
          # npm run deploy

      - name: Verify deployment
        run: |
          echo "Running production health check..."
          if ! curl -f https://developer-dashboard-ecru-nine.vercel.app; then
            echo "Deployment failed. Rolling back..."
            npm run rollback || echo "No rollback script defined"
            exit 1
          fi
